BEGIN;

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS admins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  email TEXT NOT NULL,
  senha TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'super_admin' CHECK (role IN ('super_admin')),
  criado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS admins_email_lower_unique
  ON admins (lower(email));

CREATE TABLE IF NOT EXISTS livros (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  isbn TEXT NOT NULL UNIQUE,
  nome TEXT NOT NULL,
  foto_capa BYTEA,
  foto_capa_mime TEXT CHECK (
    foto_capa_mime IS NULL OR foto_capa_mime IN ('image/jpeg', 'image/png', 'image/webp')
  ),
  descricao TEXT,
  autor TEXT NOT NULL,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT livros_capa_consistente CHECK (
    (foto_capa IS NULL AND foto_capa_mime IS NULL)
    OR (foto_capa IS NOT NULL AND foto_capa_mime IS NOT NULL)
  )
);

CREATE INDEX IF NOT EXISTS livros_nome_trgm_idx
  ON livros USING GIN (nome gin_trgm_ops);

CREATE INDEX IF NOT EXISTS livros_autor_trgm_idx
  ON livros USING GIN (autor gin_trgm_ops);

CREATE INDEX IF NOT EXISTS livros_isbn_trgm_idx
  ON livros USING GIN (isbn gin_trgm_ops);

-- O app não usa a Data API do Supabase. O backend na Vercel acessa o
-- PostgreSQL diretamente. RLS sem policies bloqueia acesso anon/authenticated.
ALTER TABLE admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE livros ENABLE ROW LEVEL SECURITY;

COMMIT;
